package devmode

import (
	"errors"
	"fmt"
	"os"
	"sort"

	"github.com/goccy/go-yaml"
)

// disableProfile is the profile name we tag disabled services with.
// Compose only starts services that have no profiles OR whose profile
// has been activated via --profile. We never activate this one, so any
// service tagged with it stays down on `localk up`.
const disableProfile = "disabled"

// DisabledOverlay is the in-memory representation of
// docker-compose.disable.yml — a sticky list of services that should
// not start when `localk up` runs the stack.
type DisabledOverlay struct {
	Services map[string]disabledEntry `yaml:"services,omitempty"`
}

// disabledEntry is the minimum-shadow of a base compose service: only
// the profiles field is set, everything else falls through from the
// base file via compose's standard overlay merge.
type disabledEntry struct {
	Profiles []string `yaml:"profiles"`
}

// LoadDisabled reads the disable overlay from path. Returns (empty
// overlay, false, nil) when the file doesn't exist — the same "valid
// missing" pattern the dev overlay uses.
func LoadDisabled(path string) (*DisabledOverlay, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return &DisabledOverlay{Services: map[string]disabledEntry{}}, false, nil
		}
		return nil, false, fmt.Errorf("reading %s: %w", path, err)
	}
	var d DisabledOverlay
	if err := yaml.Unmarshal(data, &d); err != nil {
		return nil, false, fmt.Errorf("parsing %s: %w", path, err)
	}
	if d.Services == nil {
		d.Services = map[string]disabledEntry{}
	}
	return &d, true, nil
}

// Save writes the overlay to path with a header comment. Empty
// overlay → file removed (kept tidy after the last --restore or
// --clear).
func (d *DisabledOverlay) Save(path string) error {
	if len(d.Services) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("removing empty %s: %w", path, err)
		}
		return nil
	}
	data, err := yaml.Marshal(d)
	if err != nil {
		return fmt.Errorf("marshaling overlay: %w", err)
	}
	header := []byte(
		"# docker-compose.disable.yml — generated by `localk disable`. Safe to delete.\n" +
			"# Services listed here are tagged with profiles: [\"disabled\"], so\n" +
			"# `docker compose up` skips them. Bring them back with\n" +
			"# `localk disable --restore <service>` or `localk disable --clear`.\n\n",
	)
	if err := os.WriteFile(path, append(header, data...), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// Add marks serviceName as disabled. No-op if already disabled.
func (d *DisabledOverlay) Add(serviceName string) {
	if d.Services == nil {
		d.Services = map[string]disabledEntry{}
	}
	d.Services[serviceName] = disabledEntry{Profiles: []string{disableProfile}}
}

// Remove un-disables a service. Returns true if the entry existed.
func (d *DisabledOverlay) Remove(serviceName string) bool {
	if _, ok := d.Services[serviceName]; !ok {
		return false
	}
	delete(d.Services, serviceName)
	return true
}

// Clear removes every disabled entry. Used by `localk disable --clear`.
func (d *DisabledOverlay) Clear() {
	d.Services = map[string]disabledEntry{}
}

// Names returns the sorted list of currently-disabled service names.
func (d *DisabledOverlay) Names() []string {
	out := make([]string, 0, len(d.Services))
	for name := range d.Services {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// IsDisabled reports whether serviceName is in the disabled set.
func (d *DisabledOverlay) IsDisabled(serviceName string) bool {
	_, ok := d.Services[serviceName]
	return ok
}
