// Package devmode manages the docker-compose.dev.yml overlay that puts a
// service into "dev mode" — replacing it in compose with a tiny socat
// proxy that forwards traffic to a process running on the host machine.
// Other compose services keep calling the service by its compose name;
// the proxy bridges that to the developer's local IDE.
package devmode

import (
	"errors"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/goccy/go-yaml"
)

// Overlay is the in-memory representation of docker-compose.dev.yml.
// Each entry shadows one service from the base compose file, replacing
// it with a socat-based proxy that forwards <container-port> to
// host.docker.internal:<host-port>.
type Overlay struct {
	Services map[string]ProxyService `yaml:"services,omitempty"`
}

// ProxyService is the compose-service shape for a single dev-mode
// shadow. The fields mirror the docker compose schema.
type ProxyService struct {
	Image      string   `yaml:"image"`
	Entrypoint []string `yaml:"entrypoint"`
	ExtraHosts []string `yaml:"extra_hosts,omitempty"`
	Restart    string   `yaml:"restart,omitempty"`
	// Empty Ports and DependsOn are written explicitly so the overlay
	// truly shadows whatever the base file declared (compose merges
	// arrays by default; explicit empty wins).
	Ports     []string            `yaml:"ports"`
	DependsOn map[string]struct{} `yaml:"depends_on"`
}

// Load reads the overlay file at path. Returns (empty overlay, false,
// nil) when the file doesn't exist — that's a valid state meaning "no
// services in dev mode yet."
func Load(path string) (*Overlay, bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return &Overlay{Services: map[string]ProxyService{}}, false, nil
		}
		return nil, false, fmt.Errorf("reading %s: %w", path, err)
	}
	var o Overlay
	if err := yaml.Unmarshal(data, &o); err != nil {
		return nil, false, fmt.Errorf("parsing %s: %w", path, err)
	}
	if o.Services == nil {
		o.Services = map[string]ProxyService{}
	}
	return &o, true, nil
}

// Save writes the overlay to path, with a header comment so users
// peeking at the file know what produced it. If the overlay is empty
// (no proxy entries left), the file is removed instead — keeps the
// working directory tidy after the last `--stop`.
func (o *Overlay) Save(path string) error {
	if len(o.Services) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("removing empty %s: %w", path, err)
		}
		return nil
	}
	data, err := yaml.Marshal(o)
	if err != nil {
		return fmt.Errorf("marshaling overlay: %w", err)
	}
	header := []byte(
		"# docker-compose.dev.yml — generated by `localk dev`. Safe to delete.\n" +
			"# Services listed here are running as proxies, forwarding traffic to\n" +
			"# host.docker.internal:<port> so you can run them in your IDE.\n" +
			"# `localk dev --list` shows what's currently in dev mode.\n\n",
	)
	if err := os.WriteFile(path, append(header, data...), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// AddProxy adds or replaces a proxy entry. containerPort is what the
// service listens on inside compose (other services call it on this
// port); hostPort is where the developer's IDE process is bound on
// the host machine.
func (o *Overlay) AddProxy(serviceName string, containerPort, hostPort int) {
	if o.Services == nil {
		o.Services = map[string]ProxyService{}
	}
	o.Services[serviceName] = ProxyService{
		Image: "alpine/socat:latest",
		Entrypoint: []string{
			"socat",
			"-d",
			fmt.Sprintf("TCP-LISTEN:%d,fork,reuseaddr", containerPort),
			fmt.Sprintf("TCP:host.docker.internal:%d", hostPort),
		},
		// host-gateway is needed on Linux; Mac/Windows already have
		// host.docker.internal mapped, but the entry is harmless there.
		ExtraHosts: []string{"host.docker.internal:host-gateway"},
		Restart:    "unless-stopped",
		Ports:      []string{},
		DependsOn:  map[string]struct{}{},
	}
}

// RemoveProxy removes the entry for serviceName. Returns true if an
// entry was actually removed (caller can use this to print a clearer
// "wasn't in dev mode" message).
func (o *Overlay) RemoveProxy(serviceName string) bool {
	if _, ok := o.Services[serviceName]; !ok {
		return false
	}
	delete(o.Services, serviceName)
	return true
}

// ProxyNames returns the sorted list of services currently proxied.
// Used by `localk dev --list`.
func (o *Overlay) ProxyNames() []string {
	out := make([]string, 0, len(o.Services))
	for name := range o.Services {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// ContainerPortFor parses one of compose's "host:container" port
// strings and returns the container side. Falls back to defaultPort
// when ports is empty or unparseable — most commonly the case for
// services whose host-port was stripped by the Ingress feature, where
// 80 is a sensible default since that's what k8s services typically
// listen on internally.
func ContainerPortFor(ports []string, defaultPort int) int {
	for _, p := range ports {
		// Expected form: "<host>:<container>" or "<host>:<container>/<proto>".
		s := p
		if i := strings.Index(s, "/"); i >= 0 {
			s = s[:i]
		}
		parts := strings.Split(s, ":")
		if len(parts) >= 2 {
			if n, err := strconv.Atoi(parts[len(parts)-1]); err == nil && n > 0 {
				return n
			}
		}
	}
	return defaultPort
}

// HostPortMap returns a sorted slice of (service, host-port) pairs for
// every base-compose service that publishes at least one host port.
// Used to print the "talk to other services from your laptop on these
// ports" reference list when entering dev mode.
type HostPort struct {
	Service string
	Port    int
}

func HostPortsFromBase(services map[string][]string) []HostPort {
	var out []HostPort
	for name, ports := range services {
		for _, p := range ports {
			s := p
			if i := strings.Index(s, "/"); i >= 0 {
				s = s[:i]
			}
			parts := strings.Split(s, ":")
			if len(parts) >= 2 {
				if n, err := strconv.Atoi(parts[0]); err == nil && n > 0 {
					out = append(out, HostPort{Service: name, Port: n})
					break // first published host port is enough for the reference list
				}
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Service < out[j].Service })
	return out
}

// RewriteEnvForHost walks .env-style content and rewrites occurrences
// of `<service>:<port>` to `localhost:<host-port>` when service is a
// known compose service AND the port matches one of its published
// container ports. Comments, blank lines, and unmatched values pass
// through unchanged.
//
// Designed for the printed "useful env vars" output of `localk dev`
// — best-effort, not a guarantee. Wrong rewrites are no worse than
// the user copy-pasting the raw .env themselves; correct rewrites
// save them the manual translation step.
func RewriteEnvForHost(envContent string, ports map[string][]string) string {
	// Build a service -> (container-port -> host-port) lookup once.
	lookup := map[string]map[int]int{}
	for name, pp := range ports {
		for _, p := range pp {
			s := p
			if i := strings.Index(s, "/"); i >= 0 {
				s = s[:i]
			}
			parts := strings.Split(s, ":")
			if len(parts) < 2 {
				continue
			}
			host, herr := strconv.Atoi(parts[0])
			cont, cerr := strconv.Atoi(parts[len(parts)-1])
			if herr != nil || cerr != nil {
				continue
			}
			if lookup[name] == nil {
				lookup[name] = map[int]int{}
			}
			lookup[name][cont] = host
		}
	}

	lines := strings.Split(envContent, "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		eq := strings.Index(line, "=")
		if eq < 0 {
			continue
		}
		key, val := line[:eq], line[eq+1:]
		lines[i] = key + "=" + rewriteValue(val, lookup)
	}
	return strings.Join(lines, "\n")
}

// rewriteValue is the per-value worker for RewriteEnvForHost. Walks
// the string looking for `<host>:<port>` substrings whose host is a
// known service with a matching container port; rewrites to
// `localhost:<host-port>`.
func rewriteValue(s string, lookup map[string]map[int]int) string {
	var out strings.Builder
	i := 0
	for i < len(s) {
		// Find the next potential `<host>:<port>` segment by scanning
		// for a colon. Hosts can include letters, digits, hyphen, dot.
		colon := strings.IndexByte(s[i:], ':')
		if colon < 0 {
			out.WriteString(s[i:])
			break
		}
		colon += i
		// Walk backwards to find the start of the host token.
		hostStart := colon
		for hostStart > i && isHostByte(s[hostStart-1]) {
			hostStart--
		}
		// Walk forwards to find the end of the port token.
		portStart := colon + 1
		portEnd := portStart
		for portEnd < len(s) && s[portEnd] >= '0' && s[portEnd] <= '9' {
			portEnd++
		}
		if hostStart == colon || portStart == portEnd {
			// No host or no port — emit the colon and move on.
			out.WriteString(s[i : colon+1])
			i = colon + 1
			continue
		}
		host := s[hostStart:colon]
		portStr := s[portStart:portEnd]
		port, _ := strconv.Atoi(portStr)
		if hostPort, ok := lookup[host][port]; ok {
			out.WriteString(s[i:hostStart])
			out.WriteString("localhost:")
			out.WriteString(strconv.Itoa(hostPort))
			i = portEnd
			continue
		}
		out.WriteString(s[i:portEnd])
		i = portEnd
	}
	return out.String()
}

func isHostByte(b byte) bool {
	switch {
	case b >= 'a' && b <= 'z':
		return true
	case b >= 'A' && b <= 'Z':
		return true
	case b >= '0' && b <= '9':
		return true
	case b == '-' || b == '.':
		return true
	}
	return false
}
