package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/goccy/go-yaml"

	"github.com/localk-dev/localk/internal/convert"
	"github.com/localk-dev/localk/internal/kube"
)

const usage = `localk - run your Kubernetes stack locally with one command.

Usage:
  localk generate <input-dir> [-o <output-file>]
  localk version
  localk help

Commands:
  generate    Convert k8s manifests in <input-dir> into a docker-compose.yml.
  version     Print version and exit.
  help        Print this help and exit.
`

// version is set at build time via -ldflags "-X main.version=...".
var version = "dev"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}

	switch os.Args[1] {
	case "generate":
		runGenerate(os.Args[2:])
	case "version", "-v", "--version":
		fmt.Println("localk", version)
	case "help", "-h", "--help":
		fmt.Print(usage)
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n", os.Args[1])
		fmt.Fprint(os.Stderr, usage)
		os.Exit(2)
	}
}

func runGenerate(args []string) {
	fs := flag.NewFlagSet("generate", flag.ExitOnError)
	output := fs.String("o", "docker-compose.yml", "output file path")
	envOutput := fs.String("env-out", ".env", "output file for secret-derived env vars")

	// stdlib flag stops at the first non-flag arg, which makes
	// `localk generate ./k8s -o file.yml` fail. Reorder args so all flags
	// come first, then positional args. This is a small UX win that costs
	// us nothing.
	args = reorderFlagsFirst(args)
	if err := fs.Parse(args); err != nil {
		os.Exit(2)
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "generate: missing <input-dir> argument")
		fmt.Fprintln(os.Stderr, "usage: localk generate <input-dir> [-o <output-file>]")
		os.Exit(2)
	}
	inputDir := fs.Arg(0)

	manifests, err := kube.ParseDir(inputDir)
	if err != nil {
		fail("parsing %s: %v", inputDir, err)
	}
	if len(manifests.Deployments) == 0 {
		fail("no Deployments found under %s. localk needs at least one Deployment to generate a compose file.", inputDir)
	}

	result, err := convert.Convert(manifests, nil)
	if err != nil {
		fail("converting manifests: %v", err)
	}

	composeBytes, err := yaml.Marshal(result.Compose)
	if err != nil {
		fail("marshaling compose file: %v", err)
	}

	header := []byte(
		"# Generated by localk. Do not edit by hand — regenerate from your k8s manifests instead.\n" +
			"# See https://localk.dev for documentation.\n\n",
	)
	if err := writeFile(*output, append(header, composeBytes...)); err != nil {
		fail("writing %s: %v", *output, err)
	}

	if result.EnvFile != "" {
		if err := writeFile(*envOutput, []byte(result.EnvFile)); err != nil {
			fail("writing %s: %v", *envOutput, err)
		}
	}

	abs, _ := filepath.Abs(*output)
	fmt.Printf("Wrote %s (%d services)\n", abs, len(result.Compose.Services))
	if result.EnvFile != "" {
		envAbs, _ := filepath.Abs(*envOutput)
		fmt.Printf("Wrote %s with secret-derived env vars. Review before sharing.\n", envAbs)
	}

	for _, w := range result.Warnings {
		fmt.Fprintf(os.Stderr, "warning: %s\n", w)
	}

	fmt.Println()
	fmt.Println("Next: docker compose -f", *output, "up")
}

func writeFile(path string, data []byte) error {
	return os.WriteFile(path, data, 0o644)
}

// reorderFlagsFirst pulls every -flag (and its argument when separate) to the
// front of the slice, leaving positional arguments at the back. This lets us
// accept `generate ./k8s -o out.yml` even though stdlib's flag package would
// otherwise stop parsing at `./k8s`.
//
// We only need to recognize our own flags, all of which take a string value
// and use either `-flag value` or `-flag=value` form.
func reorderFlagsFirst(args []string) []string {
	knownFlags := map[string]bool{
		"-o":         true,
		"-env-out":   true,
		"--env-out":  true,
		"--o":        true,
	}

	var flagsArgs, positional []string
	for i := 0; i < len(args); i++ {
		a := args[i]
		// `-flag=value` is self-contained.
		if eq := indexEq(a); eq > 0 && knownFlags[a[:eq]] {
			flagsArgs = append(flagsArgs, a)
			continue
		}
		if knownFlags[a] {
			flagsArgs = append(flagsArgs, a)
			if i+1 < len(args) {
				flagsArgs = append(flagsArgs, args[i+1])
				i++
			}
			continue
		}
		positional = append(positional, a)
	}
	return append(flagsArgs, positional...)
}

func indexEq(s string) int {
	for i := 0; i < len(s); i++ {
		if s[i] == '=' {
			return i
		}
	}
	return -1
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "localk: "+format+"\n", args...)
	os.Exit(1)
}
