package main

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/localk-dev/localk/internal/kube"
)

func TestResolveOutPath(t *testing.T) {
	cases := []struct {
		name string
		dir  string
		file string
		want string
	}{
		{"default cwd, default file", ".", "docker-compose.yml", "docker-compose.yml"},
		{"out-dir set, relative file", "gen", "docker-compose.yml", filepath.Join("gen", "docker-compose.yml")},
		{"out-dir set, absolute file overrides", "gen", "/tmp/foo.yml", "/tmp/foo.yml"},
		{"nested out-dir", "build/local", ".env", filepath.Join("build/local", ".env")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := resolveOutPath(tc.dir, tc.file)
			if got != tc.want {
				t.Errorf("resolveOutPath(%q, %q) = %q, want %q", tc.dir, tc.file, got, tc.want)
			}
		})
	}
}

func TestRedactEnvFile(t *testing.T) {
	in := `# Generated by localk from Kubernetes Secrets.
# Review these entries before sharing this file. Do not commit it.
DB_PASSWORD="hunter2"
JWT_SECRET="abc=def=ghi"

EMPTY_LINE_ABOVE=plainvalue
`
	got := redactEnvFile(in)

	// Comments and blank lines preserved verbatim.
	if !strings.Contains(got, "# Generated by localk from Kubernetes Secrets.") {
		t.Error("comment not preserved")
	}
	if !strings.Contains(got, "\n\n") {
		t.Error("blank line not preserved")
	}

	// Values fully redacted, even when the value itself contains '=' (the
	// redaction must split on the FIRST '=' only).
	if !strings.Contains(got, "DB_PASSWORD=<redacted>") {
		t.Errorf("DB_PASSWORD not redacted; output:\n%s", got)
	}
	if !strings.Contains(got, "JWT_SECRET=<redacted>") {
		t.Errorf("JWT_SECRET (with '=' in value) not fully redacted; output:\n%s", got)
	}

	// Original secret values must not appear anywhere in the output.
	for _, leaked := range []string{"hunter2", "abc=def=ghi", "plainvalue"} {
		if strings.Contains(got, leaked) {
			t.Errorf("secret value %q leaked into redacted output:\n%s", leaked, got)
		}
	}
}

func TestIndexEq(t *testing.T) {
	cases := []struct {
		in   string
		want int
	}{
		{"-flag=value", 5},
		{"-flag value", -1},
		{"--out-dir=foo", 9},
		{"plain", -1},
		{"=at-start", 0},
		{"", -1},
	}
	for _, tc := range cases {
		if got := indexEq(tc.in); got != tc.want {
			t.Errorf("indexEq(%q) = %d, want %d", tc.in, got, tc.want)
		}
	}
}

func TestDisplayNamespaceAndContext(t *testing.T) {
	if got := displayNamespace(""); got != "(current)" {
		t.Errorf("displayNamespace empty = %q, want (current)", got)
	}
	if got := displayNamespace("staging"); got != "staging" {
		t.Errorf("displayNamespace(staging) = %q", got)
	}
	if got := displayContext(""); got != "(current)" {
		t.Errorf("displayContext empty = %q, want (current)", got)
	}
	if got := displayContext("prod-eu1"); got != "prod-eu1" {
		t.Errorf("displayContext(prod-eu1) = %q", got)
	}
}

func TestHasWorkloads(t *testing.T) {
	cases := []struct {
		name string
		m    *kube.Manifests
		want bool
	}{
		{"empty", &kube.Manifests{}, false},
		{"only deployment", &kube.Manifests{Deployments: []kube.Deployment{{}}}, true},
		{"only statefulset", &kube.Manifests{StatefulSets: []kube.StatefulSet{{}}}, true},
		{"both", &kube.Manifests{Deployments: []kube.Deployment{{}}, StatefulSets: []kube.StatefulSet{{}}}, true},
		// Services / ConfigMaps alone aren't workloads — just supporting cast.
		{"only services", &kube.Manifests{Services: []kube.Service{{}}}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := hasWorkloads(tc.m); got != tc.want {
				t.Errorf("hasWorkloads(%s) = %v, want %v", tc.name, got, tc.want)
			}
		})
	}
}

func TestReorderFlagsFirst(t *testing.T) {
	cases := []struct {
		name string
		in   []string
		want []string
	}{
		{
			name: "positional first, flag-with-value second",
			in:   []string{"./k8s", "-o", "out.yml"},
			want: []string{"-o", "out.yml", "./k8s"},
		},
		{
			name: "positional between two flags",
			in:   []string{"-o", "out.yml", "./k8s", "--dry-run"},
			want: []string{"-o", "out.yml", "--dry-run", "./k8s"},
		},
		{
			name: "flag with = doesn't take a separate value",
			in:   []string{"./k8s", "--out-dir=build"},
			want: []string{"--out-dir=build", "./k8s"},
		},
		{
			name: "boolean flag has no value",
			in:   []string{"--dry-run", "./k8s"},
			want: []string{"--dry-run", "./k8s"},
		},
		{
			// reorderFlagsFirst only recognizes its registered flag set;
			// anything else stays where it was. This matters because if
			// it greedily reordered every -dash arg, a positional like
			// `./relative-path` would get yanked out of place.
			name: "unknown flag-looking arg is left positional",
			in:   []string{"./k8s", "-mystery"},
			want: []string{"./k8s", "-mystery"},
		},
		{
			name: "no flags, just positionals",
			in:   []string{"a", "b", "c"},
			want: []string{"a", "b", "c"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := reorderFlagsFirst(tc.in)
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("reorderFlagsFirst(%v):\n  got  %v\n  want %v", tc.in, got, tc.want)
			}
		})
	}
}

func TestMaterializedFileMode(t *testing.T) {
	cases := []struct {
		path string
		want os.FileMode
	}{
		// Bitnami helm charts mount setup scripts via subPath and exec
		// them — needs +x on the host file or Docker passes through 0644
		// and the container fails with "exec: permission denied".
		{"configs/mongodb-scripts/setup.sh", 0o755},
		{"configs/nats-config/nats.conf", 0o755},
		// Secrets stay restrictive: code reads them, never execs.
		{"secrets/tls/private.pem", 0o600},
		{"secrets/api/api-key", 0o600},
	}
	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			if got := materializedFileMode(tc.path); got != tc.want {
				t.Errorf("materializedFileMode(%q) = %o, want %o", tc.path, got, tc.want)
			}
		})
	}
}
