package main

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestResolveOutPath(t *testing.T) {
	cases := []struct {
		name string
		dir  string
		file string
		want string
	}{
		{"default cwd, default file", ".", "docker-compose.yml", "docker-compose.yml"},
		{"out-dir set, relative file", "gen", "docker-compose.yml", filepath.Join("gen", "docker-compose.yml")},
		{"out-dir set, absolute file overrides", "gen", "/tmp/foo.yml", "/tmp/foo.yml"},
		{"nested out-dir", "build/local", ".env", filepath.Join("build/local", ".env")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := resolveOutPath(tc.dir, tc.file)
			if got != tc.want {
				t.Errorf("resolveOutPath(%q, %q) = %q, want %q", tc.dir, tc.file, got, tc.want)
			}
		})
	}
}

func TestRedactEnvFile(t *testing.T) {
	in := `# Generated by localk from Kubernetes Secrets.
# Review these entries before sharing this file. Do not commit it.
DB_PASSWORD="hunter2"
JWT_SECRET="abc=def=ghi"

EMPTY_LINE_ABOVE=plainvalue
`
	got := redactEnvFile(in)

	// Comments and blank lines preserved verbatim.
	if !strings.Contains(got, "# Generated by localk from Kubernetes Secrets.") {
		t.Error("comment not preserved")
	}
	if !strings.Contains(got, "\n\n") {
		t.Error("blank line not preserved")
	}

	// Values fully redacted, even when the value itself contains '=' (the
	// redaction must split on the FIRST '=' only).
	if !strings.Contains(got, "DB_PASSWORD=<redacted>") {
		t.Errorf("DB_PASSWORD not redacted; output:\n%s", got)
	}
	if !strings.Contains(got, "JWT_SECRET=<redacted>") {
		t.Errorf("JWT_SECRET (with '=' in value) not fully redacted; output:\n%s", got)
	}

	// Original secret values must not appear anywhere in the output.
	for _, leaked := range []string{"hunter2", "abc=def=ghi", "plainvalue"} {
		if strings.Contains(got, leaked) {
			t.Errorf("secret value %q leaked into redacted output:\n%s", leaked, got)
		}
	}
}
