// Package convert translates parsed Kubernetes manifests into a docker-compose
// File. It is the heart of localk: every product decision about how a k8s
// concept maps to a compose concept lives here.
package convert

import (
	"encoding/base64"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/localk-dev/localk/internal/compose"
	"github.com/localk-dev/localk/internal/config"
	"github.com/localk-dev/localk/internal/kube"
)

// Result is the output of a conversion run: the compose file plus a sidecar
// .env content for secret values, an optional Caddyfile when the input
// includes Ingresses, plus any warnings the user should see.
type Result struct {
	Compose   *compose.File
	EnvFile   string // contents to write to .env (may be empty)
	CaddyFile string // contents to write to Caddyfile (empty when no Ingress)
	// ConfigFiles maps relative paths (under the out-dir) to file
	// contents. Populated when k8s ConfigMaps and Secrets are
	// referenced as volume mounts: each key in the resource becomes
	// one file on disk, and the service gets a bind-mount entry
	// pointing at the directory. Compose has no native equivalent
	// of "mount this configmap data as files," so we materialize.
	ConfigFiles map[string]string
	Warnings    []string
}

// Convert translates the given Manifests bundle into a Result. The optional
// cfg applies per-service overrides (skip, image, build) loaded from
// localk.yaml; pass nil for "no overrides".
func Convert(m *kube.Manifests, cfg *config.Config) (*Result, error) {
	res := &Result{
		Compose: &compose.File{
			Services: map[string]compose.Service{},
			Volumes:  map[string]compose.Volume{},
		},
		ConfigFiles: map[string]string{},
	}

	// Track which volumes we have declared at the top level so we don't
	// duplicate. PVCs always become named volumes; emptyDir becomes anonymous.
	declaredVolumes := map[string]bool{}

	// Aggregate secret values into a single .env block. Compose has no
	// first-class equivalent of a Kubernetes Secret, so we surface them as
	// environment variables in a .env file with a clear warning.
	envFileLines := []string{}
	envFileSeen := map[string]bool{}

	// Track which override entries actually matched a deployment, so we can
	// warn about typos / stale entries at the end.
	overrideHits := map[string]bool{}

	for i := range m.Deployments {
		w := workloadFromDeployment(&m.Deployments[i])
		if err := convertWorkload(w, m, cfg, declaredVolumes, overrideHits, &envFileLines, envFileSeen, res); err != nil {
			return nil, err
		}
	}

	for i := range m.StatefulSets {
		w := workloadFromStatefulSet(&m.StatefulSets[i])
		if err := convertWorkload(w, m, cfg, declaredVolumes, overrideHits, &envFileLines, envFileSeen, res); err != nil {
			return nil, err
		}
	}

	for name := range cfg.ServiceNames() {
		if !overrideHits[name] {
			res.Warnings = append(res.Warnings, fmt.Sprintf(
				"localk.yaml: override for service %q did not match any Deployment or StatefulSet in the input. Typo or stale entry?",
				name,
			))
		}
	}

	if len(envFileLines) > 0 {
		header := "# Generated by localk from Kubernetes Secrets.\n" +
			"# Review these values before sharing this file. Do not commit it.\n"
		res.EnvFile = header + strings.Join(envFileLines, "\n") + "\n"
	}

	// Ingress → Caddy proxy. Done last so we can see all converted services
	// when resolving backends. Also strips host-port publishing from any
	// service that becomes an Ingress backend so they don't fight the proxy
	// for host:80.
	proxy, caddyfile, backends, ingressWarnings := buildProxy(m.Ingresses, res.Compose.Services)
	res.Warnings = append(res.Warnings, ingressWarnings...)
	if proxy != nil {
		stripBackendPorts(res.Compose.Services, backends)
		res.Compose.Services[proxyServiceName] = *proxy
		res.CaddyFile = caddyfile
	}

	// Final pass: resolve any remaining host-port conflicts. Multiple
	// services declaring the same host port (with or without an
	// Ingress in the picture) would otherwise crash compose at `up`
	// time on the second bind.
	res.Warnings = append(res.Warnings, resolveHostPortConflicts(res.Compose.Services)...)

	return res, nil
}

// applyServiceOverride mutates svc in-place to reflect the user's localk.yaml
// settings. The override fields are mutually compatible — image and build
// both clear the other (build wins if both are set, but the config layer
// could reject that in the future).
func applyServiceOverride(svc *compose.Service, ov config.ServiceOverride) {
	if ov.Image != "" {
		svc.Image = ov.Image
		svc.Build = nil
	}
	if ov.Build != nil {
		svc.Image = ""
		svc.Build = &compose.Build{
			Context:    ov.Build.Context,
			Dockerfile: ov.Build.Dockerfile,
		}
	}
}

// workload is the common shape we extract from both Deployments and
// StatefulSets so the converter doesn't need to branch on the resource kind.
// Replicas don't translate to compose, so we drop them entirely; what
// matters is the pod template (containers, env, volumes) plus any
// volumeClaimTemplates that need to materialize as named compose volumes.
type workload struct {
	kindLabel    string // "deployment" / "statefulset", used in warning messages
	name         string // metadata.name from the workload
	pod          kube.PodTemplate
	volumeClaims []kube.PersistentVolumeClaimTemplate
}

func workloadFromDeployment(d *kube.Deployment) workload {
	return workload{
		kindLabel: "deployment",
		name:      d.Metadata.Name,
		pod:       d.Spec.Template,
	}
}

func workloadFromStatefulSet(s *kube.StatefulSet) workload {
	return workload{
		kindLabel:    "statefulset",
		name:         s.Metadata.Name,
		pod:          s.Spec.Template,
		volumeClaims: s.Spec.VolumeClaimTemplates,
	}
}

// allVolumes returns the pod's declared volumes plus a synthetic kube.Volume
// for each volumeClaimTemplate. The synthetic volume is shaped like a
// regular PVC reference so the existing volume conversion path doesn't have
// to know about VCTs at all — by the time it runs, every container
// volumeMount has a matching entry here.
//
// We use the workload's own name as the claim-name prefix to ensure
// uniqueness when multiple StatefulSets in the same input declare a VCT
// with the same metadata.name (e.g. two different services both calling
// their data volume "data").
func (w workload) allVolumes() []kube.Volume {
	if len(w.volumeClaims) == 0 {
		return w.pod.Spec.Volumes
	}
	out := make([]kube.Volume, 0, len(w.pod.Spec.Volumes)+len(w.volumeClaims))
	out = append(out, w.pod.Spec.Volumes...)
	for _, vct := range w.volumeClaims {
		claim := w.name + "-" + vct.Metadata.Name
		out = append(out, kube.Volume{
			Name: vct.Metadata.Name,
			PVC:  &kube.PVCVolSource{ClaimName: claim},
		})
	}
	return out
}

// convertWorkload runs one workload (Deployment or StatefulSet) through the
// pipeline: resolve service name, apply localk.yaml override, convert pod
// template, attach VCT-derived volumes, register the result.
func convertWorkload(
	w workload,
	m *kube.Manifests,
	cfg *config.Config,
	declaredVolumes map[string]bool,
	overrideHits map[string]bool,
	envFileLines *[]string,
	envFileSeen map[string]bool,
	res *Result,
) error {
	name := serviceName(w, m)
	override := cfg.ServiceOverrideFor(name)
	if override.Skip || override.Image != "" || override.Build != nil {
		overrideHits[name] = true
	}
	if override.Skip {
		return nil
	}

	main, extras, warnings, err := convertPod(w, name, m, declaredVolumes, res.Compose, envFileLines, envFileSeen, res.ConfigFiles)
	if err != nil {
		return err
	}
	res.Warnings = append(res.Warnings, warnings...)

	applyServiceOverride(&main, override)
	res.Compose.Services[name] = main
	for extraName, extra := range extras {
		res.Compose.Services[extraName] = extra
	}
	return nil
}

// serviceName decides what to call a workload in the compose file. We prefer
// the matched Service's name (which is what other services use as a hostname
// in production) over the workload's own name, so DNS continuity is
// preserved locally.
func serviceName(w workload, m *kube.Manifests) string {
	if svc := m.FindServiceForSelector(w.pod.Metadata.Labels); svc != nil {
		return svc.Metadata.Name
	}
	return w.name
}

// convertPod walks every container in the pod and produces:
//   - main: the compose service for containers[0], named after the workload
//   - sidecars: a map of <main>-<container.Name> → compose.Service for any
//     additional containers, sharing main's network namespace via
//     network_mode: service:<main>. This mirrors the k8s pod model where
//     all containers share an IP and reach each other on localhost.
func convertPod(
	w workload,
	mainName string,
	m *kube.Manifests,
	declaredVolumes map[string]bool,
	out *compose.File,
	envFileLines *[]string,
	envFileSeen map[string]bool,
	configFiles map[string]string,
) (compose.Service, map[string]compose.Service, []string, error) {
	var warnings []string

	containers := w.pod.Spec.Containers
	if len(containers) == 0 {
		return compose.Service{}, nil, nil, fmt.Errorf("%s %s has no containers", w.kindLabel, w.name)
	}

	// Pre-pass: identify volumes mounted by 2+ containers (main, sidecars,
	// or initContainers). These become shared scratch space — typical
	// patterns are "main writes logs, sidecar tails them" and "init
	// writes config, main reads it." Without promotion to a named volume,
	// each compose service gets its own anonymous mount and sharing
	// silently breaks.
	allContainers := append([]kube.Container{}, w.pod.Spec.InitContainers...)
	allContainers = append(allContainers, containers...)
	shared := sharedVolumeNames(allContainers)

	extras := map[string]compose.Service{}

	// --- Init containers (run in declaration order, must complete before
	// main starts). Each init becomes a one-shot compose service with
	// restart: "no", and they form a depends_on chain so docker compose
	// runs them sequentially. The main service then depends_on the last
	// init with condition: service_completed_successfully.
	var initNames []string
	for i, c := range w.pod.Spec.InitContainers {
		s, w2 := buildContainerService(c, w, m, declaredVolumes, out, envFileLines, envFileSeen, shared, configFiles)
		warnings = append(warnings, w2...)
		s.Restart = "no"
		name := mainName + "-" + c.Name
		if i > 0 {
			s.DependsOn = map[string]compose.DependsOnSpec{
				initNames[i-1]: {Condition: "service_completed_successfully"},
			}
		}
		extras[name] = s
		initNames = append(initNames, name)
	}

	// --- Main container.
	main, mainWarnings := buildContainerService(containers[0], w, m, declaredVolumes, out, envFileLines, envFileSeen, shared, configFiles)
	warnings = append(warnings, mainWarnings...)

	// Service-derived ports are published only by the main's service.
	// Sidecars share that namespace, so a single host:port mapping covers
	// the whole pod.
	if matched := m.FindServiceForSelector(w.pod.Metadata.Labels); matched != nil {
		for _, p := range matched.Spec.Ports {
			target := containerPortFromService(p, containers[0])
			main.Ports = append(main.Ports, fmt.Sprintf("%d:%d", p.Port, target))
		}
	}
	if len(initNames) > 0 {
		main.DependsOn = map[string]compose.DependsOnSpec{
			initNames[len(initNames)-1]: {Condition: "service_completed_successfully"},
		}
	}

	// --- Sidecars (run alongside main, sharing its network namespace).
	for _, c := range containers[1:] {
		sc, scWarnings := buildContainerService(c, w, m, declaredVolumes, out, envFileLines, envFileSeen, shared, configFiles)
		warnings = append(warnings, scWarnings...)
		sc.NetworkMode = "service:" + mainName
		extras[mainName+"-"+c.Name] = sc
	}

	return main, extras, warnings, nil
}

// buildContainerService converts one k8s container into a generic compose
// Service — env, env_file, volumes, resource limits — with no role-specific
// tweaks. The caller decides what to do with the result based on whether
// the container is the main, a sidecar (set NetworkMode, drop Ports), or an
// init container (Restart="no", wire depends_on).
func buildContainerService(
	c kube.Container,
	w workload,
	m *kube.Manifests,
	declaredVolumes map[string]bool,
	out *compose.File,
	envFileLines *[]string,
	envFileSeen map[string]bool,
	shared map[string]bool,
	configFiles map[string]string,
) (compose.Service, []string) {
	var warnings []string

	svc := compose.Service{
		Image:   c.Image,
		Restart: "unless-stopped",
	}
	// k8s command/args are shell strings meant for the container's
	// runtime to evaluate. Compose, however, runs an interpolation
	// pass over every string in the YAML at parse time and tries to
	// substitute `$VAR` / `${VAR}` / `$(cmd)` from its OWN env. To
	// keep the shell payload intact we escape every `$` to `$$`
	// (compose's documented escape) so it reaches the container
	// verbatim and the container's `sh` does the right thing at run
	// time. Same pattern applied to env values below.
	if len(c.Command) > 0 {
		svc.Entrypoint = escapeShellArgs(c.Command)
	}
	if len(c.Args) > 0 {
		svc.Command = escapeShellArgs(c.Args)
	}

	// --- Environment ---
	env := map[string]string{}

	// envFrom comes first so explicit env entries can override.
	for _, ef := range c.EnvFrom {
		switch {
		case ef.ConfigMapRef != nil:
			cm := m.FindConfigMap(ef.ConfigMapRef.Name)
			if cm == nil {
				warnings = append(warnings, fmt.Sprintf(
					"%s %q references ConfigMap %q via envFrom but it is not defined in the input",
					w.kindLabel, w.name, ef.ConfigMapRef.Name,
				))
				continue
			}
			for k, v := range cm.Data {
				env[ef.Prefix+k] = v
			}
		case ef.SecretRef != nil:
			sec := m.FindSecret(ef.SecretRef.Name)
			if sec == nil {
				warnings = append(warnings, fmt.Sprintf(
					"%s %q references Secret %q via envFrom but it is not defined in the input",
					w.kindLabel, w.name, ef.SecretRef.Name,
				))
				continue
			}
			for k, v := range secretValues(sec) {
				key := ef.Prefix + k
				addEnvFileLine(envFileLines, envFileSeen, key, v)
			}
			svc.EnvFile = appendUnique(svc.EnvFile, ".env")
		}
	}

	// Walk env entries in declaration order so $(VAR) references inside a
	// later value can resolve against earlier env vars (the same semantics
	// k8s applies at pod startup).
	for _, e := range c.Env {
		switch {
		case e.ValueFrom == nil:
			env[e.Name] = expandRefs(e.Value, env)
		case e.ValueFrom.FieldRef != nil:
			v, ok := resolveFieldRef(e.ValueFrom.FieldRef.FieldPath, w)
			if !ok {
				warnings = append(warnings, fmt.Sprintf(
					"env %q in %s %q uses fieldPath %q which has no local equivalent; leaving unset",
					e.Name, w.kindLabel, w.name, e.ValueFrom.FieldRef.FieldPath,
				))
				continue
			}
			env[e.Name] = v
		case e.ValueFrom.ConfigMapKeyRef != nil:
			ref := e.ValueFrom.ConfigMapKeyRef
			cm := m.FindConfigMap(ref.Name)
			if cm == nil {
				warnings = append(warnings, fmt.Sprintf(
					"env %q in %s %q references ConfigMap %q which is not defined",
					e.Name, w.kindLabel, w.name, ref.Name,
				))
				continue
			}
			env[e.Name] = cm.Data[ref.Key]
		case e.ValueFrom.SecretKeyRef != nil:
			ref := e.ValueFrom.SecretKeyRef
			sec := m.FindSecret(ref.Name)
			if sec == nil {
				warnings = append(warnings, fmt.Sprintf(
					"env %q in %s %q references Secret %q which is not defined",
					e.Name, w.kindLabel, w.name, ref.Name,
				))
				continue
			}
			vals := secretValues(sec)
			addEnvFileLine(envFileLines, envFileSeen, e.Name, vals[ref.Key])
			svc.EnvFile = appendUnique(svc.EnvFile, ".env")
		}
	}
	if len(env) > 0 {
		// Compose interpolates `$VAR` / `${VAR}` patterns in env
		// values at parse time. After expandRefs has resolved any
		// k8s `$(VAR)` downward-API references, the only `$` left
		// in a value is meant to reach the container literally —
		// either it's a shell variable for the container to expand
		// at runtime (`$XDG_CONFIG_HOME` in nats-box bootstrap), or
		// it's part of a value (`pass$word`). Both want to survive
		// compose's interpolation pass, so we double the dollars.
		svc.Environment = escapeEnvValues(env)
	}

	// --- Volumes ---
	for _, vm := range c.VolumeMounts {
		volSrc := findVolume(w.allVolumes(), vm.Name)
		if volSrc == nil {
			warnings = append(warnings, fmt.Sprintf(
				"%s %q has volumeMount %q with no matching volume in the pod spec",
				w.kindLabel, w.name, vm.Name,
			))
			continue
		}
		entry, declareName, declared, files, perEntryWarnings := volumeEntryFor(volSrc, vm, shared, w.name, m)
		if entry != "" {
			svc.Volumes = append(svc.Volumes, entry)
		}
		if declared && !declaredVolumes[declareName] {
			out.Volumes[declareName] = compose.Volume{}
			declaredVolumes[declareName] = true
		}
		// Merge any materialized ConfigMap/Secret files into the
		// shared map. Same CM mounted in multiple containers is a
		// no-op write; each key produces the same content.
		for path, content := range files {
			configFiles[path] = content
		}
		warnings = append(warnings, perEntryWarnings...)
	}

	// --- Resource limits ---
	if c.Resources.Limits.Memory != "" || c.Resources.Limits.CPU != "" {
		svc.Deploy = &compose.Deploy{
			Resources: compose.DeployResources{
				Limits: &compose.ResourceSpec{
					CPUs:   normalizeCPU(c.Resources.Limits.CPU),
					Memory: normalizeMemory(c.Resources.Limits.Memory),
				},
			},
		}
	}

	sort.Strings(svc.EnvFile)
	return svc, warnings
}

// sharedVolumeNames returns the set of pod volume names referenced by 2+
// containers — the candidates for promoting an emptyDir to a named volume
// so all containers see the same data.
func sharedVolumeNames(containers []kube.Container) map[string]bool {
	count := map[string]int{}
	for _, c := range containers {
		seen := map[string]bool{} // dedupe within a single container
		for _, vm := range c.VolumeMounts {
			if !seen[vm.Name] {
				seen[vm.Name] = true
				count[vm.Name]++
			}
		}
	}
	out := map[string]bool{}
	for name, n := range count {
		if n > 1 {
			out[name] = true
		}
	}
	return out
}

func findVolume(vols []kube.Volume, name string) *kube.Volume {
	for i := range vols {
		if vols[i].Name == name {
			return &vols[i]
		}
	}
	return nil
}

// volumeEntryFor returns the compose-side volume mount info for a
// given k8s volume reference, plus any files that need to be
// materialized on disk (for ConfigMap/Secret-backed volumes which
// have no native compose equivalent — we write the data to files
// under the out-dir and bind-mount the directory).
//
// Returns:
//   - mount: the entry to append to the service's `volumes:` list
//     (empty string = no mount, e.g. for unsupported types)
//   - declareName: name of a top-level volume to declare (PVCs and
//     promoted shared emptyDirs); empty when no top-level decl
//   - declared: whether the caller should add declareName to volumes
//   - files: relative-path → content to write before `up` (under the
//     out-dir's `configs/` or `secrets/` tree)
//   - warnings: things the user should know (missing CM/Secret refs,
//     mostly)
//
// shared lists volume names referenced by 2+ containers in the same
// pod. When an emptyDir falls into that set we promote it to a named
// compose volume (prefixed with the workload name to avoid collisions)
// so every container sharing it sees the same data.
func volumeEntryFor(v *kube.Volume, vm kube.VolumeMount, shared map[string]bool, workloadName string, m *kube.Manifests) (string, string, bool, map[string]string, []string) {
	switch {
	case v.PVC != nil:
		return fmt.Sprintf("%s:%s", v.PVC.ClaimName, vm.MountPath), v.PVC.ClaimName, true, nil, nil
	case v.EmptyDir != nil:
		if shared[v.Name] {
			named := workloadName + "-" + v.Name
			return fmt.Sprintf("%s:%s", named, vm.MountPath), named, true, nil, nil
		}
		return vm.MountPath, "", false, nil, nil
	case v.HostPath != nil:
		return fmt.Sprintf("%s:%s", v.HostPath.Path, vm.MountPath), "", false, nil, nil
	case v.ConfigMap != nil:
		return materializeConfigMap(v.ConfigMap.Name, vm, m)
	case v.Secret != nil:
		return materializeSecret(v.Secret.SecretName, vm, m)
	}
	return "", "", false, nil, nil
}

// materializeConfigMap turns a `volumes: { configMap: { name: X } }`
// reference into:
//   - a bind-mount entry pointing at out-dir/configs/X
//   - one file per key in the ConfigMap's data
//
// The mount is read-only because k8s defaults configMap volumes to
// read-only — apps that try to write back would silently succeed
// locally and fail in prod, which is a worse failure mode than just
// rejecting writes everywhere.
func materializeConfigMap(name string, vm kube.VolumeMount, m *kube.Manifests) (string, string, bool, map[string]string, []string) {
	cm := m.FindConfigMap(name)
	if cm == nil {
		return "", "", false, nil, []string{fmt.Sprintf(
			"volumeMount %q references ConfigMap %q which is not defined; skipping the mount (the container will see an empty directory at %s)",
			vm.Name, name, vm.MountPath,
		)}
	}
	files := map[string]string{}
	for key, val := range cm.Data {
		files[fmt.Sprintf("configs/%s/%s", name, key)] = val
	}
	mount := fmt.Sprintf("./configs/%s:%s:ro", name, vm.MountPath)
	return mount, "", false, files, nil
}

// materializeSecret is the Secret-volume sibling of materializeConfigMap.
// Decodes base64 data + merges stringData (matching k8s semantics)
// before writing files. A warning surfaces because the resulting
// files contain real secret values — same hazard the .env file
// already has, restated for the volume case so users don't miss it.
func materializeSecret(name string, vm kube.VolumeMount, m *kube.Manifests) (string, string, bool, map[string]string, []string) {
	sec := m.FindSecret(name)
	if sec == nil {
		return "", "", false, nil, []string{fmt.Sprintf(
			"volumeMount %q references Secret %q which is not defined; skipping the mount",
			vm.Name, name,
		)}
	}
	values := secretValues(sec) // existing helper: merges Data (b64) and StringData
	files := map[string]string{}
	for key, val := range values {
		files[fmt.Sprintf("secrets/%s/%s", name, key)] = val
	}
	mount := fmt.Sprintf("./secrets/%s:%s:ro", name, vm.MountPath)
	warning := fmt.Sprintf(
		"Secret %q materialized as files under secrets/%s/. These are real cluster secret values — add `secrets/` to .gitignore and never commit them.",
		name, name,
	)
	return mount, "", false, files, []string{warning}
}

// containerPortFromService picks the right container-side port for a Service
// port mapping. If targetPort is set and numeric, use it. If it's a string,
// look up the named port in the container. Otherwise default to the service
// port itself.
func containerPortFromService(p kube.ServicePort, c kube.Container) int32 {
	if p.TargetPort == nil {
		return p.Port
	}
	switch v := p.TargetPort.(type) {
	case int:
		return int32(v)
	case int32:
		return v
	case int64:
		return int32(v)
	case string:
		// numeric string?
		if n, err := strconv.Atoi(v); err == nil {
			return int32(n)
		}
		// named port — look it up in the container's port list
		for _, cp := range c.Ports {
			if cp.Name == v {
				return cp.ContainerPort
			}
		}
	}
	return p.Port
}

// secretValues returns the decoded key/value pairs from a Secret, merging
// stringData (plain) and data (base64-encoded). stringData wins on conflict,
// matching Kubernetes' own semantics.
func secretValues(s *kube.Secret) map[string]string {
	out := map[string]string{}
	for k, v := range s.Data {
		dec, err := base64.StdEncoding.DecodeString(v)
		if err == nil {
			out[k] = string(dec)
		} else {
			// Not base64 — pass through as-is. Some manifests do this.
			out[k] = v
		}
	}
	for k, v := range s.StringData {
		out[k] = v
	}
	return out
}

func addEnvFileLine(lines *[]string, seen map[string]bool, key, value string) {
	if seen[key] {
		return
	}
	seen[key] = true
	// Quote the value to be safe; we escape any embedded double quotes.
	escaped := strings.ReplaceAll(value, `"`, `\"`)
	*lines = append(*lines, fmt.Sprintf(`%s="%s"`, key, escaped))
}

func appendUnique(slice []string, item string) []string {
	for _, s := range slice {
		if s == item {
			return slice
		}
	}
	return append(slice, item)
}

// normalizeCPU converts a k8s CPU quantity ("500m", "1") into a compose-style
// fractional CPU string ("0.5", "1.0"). Compose accepts fractional cpus.
func normalizeCPU(s string) string {
	if s == "" {
		return ""
	}
	if strings.HasSuffix(s, "m") {
		num := strings.TrimSuffix(s, "m")
		if n, err := strconv.Atoi(num); err == nil {
			return fmt.Sprintf("%.3f", float64(n)/1000.0)
		}
	}
	return s
}

// escapeShellArgs doubles every `$` in each element so compose's
// parse-time variable interpolation leaves the args alone. The
// escape is compose's own (`$$` → literal `$`); the container's
// shell never sees the doubled form because compose un-escapes
// before passing the args to the container.
func escapeShellArgs(args []string) []string {
	if len(args) == 0 {
		return args
	}
	out := make([]string, len(args))
	for i, a := range args {
		out[i] = escapeDollars(a)
	}
	return out
}

// escapeEnvValues runs the same escape over the values of an env
// map. Keys are left untouched (env-var names can't contain `$` in
// any sane setup).
func escapeEnvValues(env map[string]string) map[string]string {
	out := make(map[string]string, len(env))
	for k, v := range env {
		out[k] = escapeDollars(v)
	}
	return out
}

// escapeDollars replaces every `$` with `$$`. We don't try to be
// clever about which dollars are "real" shell variables vs. literal
// — compose treats every `$` as an interpolation trigger, so every
// `$` we want to pass through needs the escape.
func escapeDollars(s string) string {
	if !strings.Contains(s, "$") {
		return s
	}
	return strings.ReplaceAll(s, "$", "$$")
}

// normalizeMemory converts a k8s memory quantity to a compose-compatible
// integer-bytes string.
//
// k8s and compose use different memory unit grammars:
//   - k8s accepts both binary (Ki, Mi, Gi, Ti — powers of 1024) and decimal
//     (K, M, G, T — powers of 1000) suffixes.
//   - compose accepts only decimal suffixes (b, k/kb, m/mb, g/gb) plus plain
//     bytes as a number. Binary suffixes (Mi/Gi) are rejected with
//     "invalid suffix" — that's the bug this fixes.
//
// We normalize to plain bytes, which compose accepts losslessly. The
// generated YAML reads "536870912" instead of "512Mi" — less friendly to
// eyeball but unambiguous and correct on every compose version. Comments
// in the generated file already point users at `localk generate` rather
// than hand-editing, so readability of the byte count isn't a real
// regression.
//
// Unknown / unparseable inputs pass through unchanged so a future k8s
// suffix or a malformed value surfaces as a compose error rather than
// silently dropping the limit.
func normalizeMemory(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	i := 0
	for i < len(s) && (s[i] == '.' || (s[i] >= '0' && s[i] <= '9')) {
		i++
	}
	if i == 0 || i == len(s) {
		// No leading digits, or no suffix to convert — pass through.
		return s
	}
	valStr, suffix := s[:i], s[i:]

	var multiplier int64
	switch strings.ToLower(suffix) {
	case "ki":
		multiplier = 1 << 10
	case "mi":
		multiplier = 1 << 20
	case "gi":
		multiplier = 1 << 30
	case "ti":
		multiplier = 1 << 40
	case "k":
		multiplier = 1000
	case "m":
		multiplier = 1000 * 1000
	case "g":
		multiplier = 1000 * 1000 * 1000
	case "t":
		multiplier = 1000 * 1000 * 1000 * 1000
	default:
		return s
	}

	val, err := strconv.ParseFloat(valStr, 64)
	if err != nil {
		return s
	}
	return strconv.FormatInt(int64(val*float64(multiplier)), 10)
}
