// Package convert translates parsed Kubernetes manifests into a docker-compose
// File. It is the heart of localk: every product decision about how a k8s
// concept maps to a compose concept lives here.
package convert

import (
	"encoding/base64"
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"github.com/localk-dev/localk/internal/compose"
	"github.com/localk-dev/localk/internal/config"
	"github.com/localk-dev/localk/internal/kube"
)

// Result is the output of a conversion run: the compose file plus a sidecar
// .env content for secret values, an optional Caddyfile when the input
// includes Ingresses, plus any warnings the user should see.
type Result struct {
	Compose   *compose.File
	EnvFile   string // contents to write to .env (may be empty)
	CaddyFile string // contents to write to Caddyfile (empty when no Ingress)
	// ConfigFiles maps relative paths (under the out-dir) to file
	// contents. Populated when k8s ConfigMaps and Secrets are
	// referenced as volume mounts: each key in the resource becomes
	// one file on disk, and the service gets a bind-mount entry
	// pointing at the directory. Compose has no native equivalent
	// of "mount this configmap data as files," so we materialize.
	ConfigFiles map[string]string
	// EmptyDirs is the set of relative directories under the out-dir
	// that back emptyDir volume mounts. The CLI mkdir's each one
	// with mode 0777 before docker compose up. Bind-mount here so
	// any container UID can read/write (k8s would set fsGroup
	// ownership; compose has no equivalent), and so init→main
	// shares via the host filesystem the way k8s shares via the
	// kubelet's emptyDir backing.
	EmptyDirs map[string]bool
	// SwappedServices lists services whose image was replaced by
	// the dev-swap (Bitnami clustered chart → vanilla upstream).
	// ApplyPlatform consults this to avoid pinning linux/amd64 on
	// images we know ship multi-arch builds (mongo, rabbitmq, …).
	// Forcing those through Rosetta on Apple Silicon is both slow
	// and bug-prone (mongo:7's first-stage setup mongod fails on
	// bind() with EINVAL under amd64 emulation).
	SwappedServices map[string]bool
	Warnings        []string
}

// Convert translates the given Manifests bundle into a Result. The optional
// cfg applies per-service overrides (skip, image, build) loaded from
// localk.yaml; pass nil for "no overrides".
func Convert(m *kube.Manifests, cfg *config.Config) (*Result, error) {
	res := &Result{
		Compose: &compose.File{
			Services: map[string]compose.Service{},
			Volumes:  map[string]compose.Volume{},
		},
		ConfigFiles:     map[string]string{},
		EmptyDirs:       map[string]bool{},
		SwappedServices: map[string]bool{},
	}

	// Track which volumes we have declared at the top level so we don't
	// duplicate. PVCs always become named volumes; emptyDir becomes anonymous.
	declaredVolumes := map[string]bool{}

	// Aggregate secret values into a single .env block. Compose has no
	// first-class equivalent of a Kubernetes Secret, so we surface them as
	// environment variables in a .env file with a clear warning.
	envFileLines := []string{}
	envFileSeen := map[string]bool{}

	// Track which override entries actually matched a deployment, so we can
	// warn about typos / stale entries at the end.
	overrideHits := map[string]bool{}

	for i := range m.Deployments {
		w := workloadFromDeployment(&m.Deployments[i])
		if err := convertWorkload(w, m, cfg, declaredVolumes, overrideHits, &envFileLines, envFileSeen, res); err != nil {
			return nil, err
		}
	}

	for i := range m.StatefulSets {
		w := workloadFromStatefulSet(&m.StatefulSets[i])
		if err := convertWorkload(w, m, cfg, declaredVolumes, overrideHits, &envFileLines, envFileSeen, res); err != nil {
			return nil, err
		}
	}

	for name := range cfg.ServiceNames() {
		if !overrideHits[name] {
			res.Warnings = append(res.Warnings, fmt.Sprintf(
				"localk.yaml: override for service %q did not match any Deployment or StatefulSet in the input. Typo or stale entry?",
				name,
			))
		}
	}

	if len(envFileLines) > 0 {
		header := "# Generated by localk from Kubernetes Secrets.\n" +
			"# Review these values before sharing this file. Do not commit it.\n"
		res.EnvFile = header + strings.Join(envFileLines, "\n") + "\n"
	}

	// Ingress → Caddy proxy. Done last so we can see all converted services
	// when resolving backends. Also strips host-port publishing from any
	// service that becomes an Ingress backend so they don't fight the proxy
	// for host:80.
	proxy, caddyfile, backends, ingressWarnings := buildProxy(m.Ingresses, res.Compose.Services)
	res.Warnings = append(res.Warnings, ingressWarnings...)
	if proxy != nil {
		stripBackendPorts(res.Compose.Services, backends)
		res.Compose.Services[proxyServiceName] = *proxy
		res.CaddyFile = caddyfile
	}

	// Final pass: resolve any remaining host-port conflicts. Multiple
	// services declaring the same host port (with or without an
	// Ingress in the picture) would otherwise crash compose at `up`
	// time on the second bind.
	res.Warnings = append(res.Warnings, resolveHostPortConflicts(res.Compose.Services)...)

	return res, nil
}

// applyServiceOverride mutates svc in-place to reflect the user's localk.yaml
// settings. The override fields are mutually compatible — image and build
// both clear the other (build wins if both are set, but the config layer
// could reject that in the future).
func applyServiceOverride(svc *compose.Service, ov config.ServiceOverride) {
	if ov.Image != "" {
		svc.Image = ov.Image
		svc.Build = nil
	}
	if ov.Build != nil {
		svc.Image = ""
		svc.Build = &compose.Build{
			Context:    ov.Build.Context,
			Dockerfile: ov.Build.Dockerfile,
		}
	}
}

// workload is the common shape we extract from both Deployments and
// StatefulSets so the converter doesn't need to branch on the resource kind.
// Replicas don't translate to compose, so we drop them entirely; what
// matters is the pod template (containers, env, volumes) plus any
// volumeClaimTemplates that need to materialize as named compose volumes.
type workload struct {
	kindLabel string // "deployment" / "statefulset", used in warning messages
	name      string // metadata.name from the workload
	namespace string // metadata.namespace, "" means "default"
	// replicas is the workload's replica count, used when generating
	// StatefulSet pod-N FQDN aliases (mongodb-0, mongodb-1, ...).
	// 0 means "compose still runs a single container" — but the alias
	// list still needs to cover any pod ordinal that other services
	// might address via cluster DNS, so we treat 0 as 1.
	replicas     int32
	pod          kube.PodTemplate
	volumeClaims []kube.PersistentVolumeClaimTemplate
}

func workloadFromDeployment(d *kube.Deployment) workload {
	return workload{
		kindLabel: "deployment",
		name:      d.Metadata.Name,
		namespace: d.Metadata.Namespace,
		replicas:  d.Spec.Replicas,
		pod:       d.Spec.Template,
	}
}

func workloadFromStatefulSet(s *kube.StatefulSet) workload {
	return workload{
		kindLabel:    "statefulset",
		name:         s.Metadata.Name,
		namespace:    s.Metadata.Namespace,
		replicas:     s.Spec.Replicas,
		pod:          s.Spec.Template,
		volumeClaims: s.Spec.VolumeClaimTemplates,
	}
}

// allVolumes returns the pod's declared volumes plus a synthetic kube.Volume
// for each volumeClaimTemplate. The synthetic volume is shaped like a
// regular PVC reference so the existing volume conversion path doesn't have
// to know about VCTs at all — by the time it runs, every container
// volumeMount has a matching entry here.
//
// We use the workload's own name as the claim-name prefix to ensure
// uniqueness when multiple StatefulSets in the same input declare a VCT
// with the same metadata.name (e.g. two different services both calling
// their data volume "data").
func (w workload) allVolumes() []kube.Volume {
	if len(w.volumeClaims) == 0 {
		return w.pod.Spec.Volumes
	}
	out := make([]kube.Volume, 0, len(w.pod.Spec.Volumes)+len(w.volumeClaims))
	out = append(out, w.pod.Spec.Volumes...)
	for _, vct := range w.volumeClaims {
		claim := w.name + "-" + vct.Metadata.Name
		out = append(out, kube.Volume{
			Name: vct.Metadata.Name,
			PVC:  &kube.PVCVolSource{ClaimName: claim},
		})
	}
	return out
}

// convertWorkload runs one workload (Deployment or StatefulSet) through the
// pipeline: resolve service name, apply localk.yaml override, convert pod
// template, attach VCT-derived volumes, register the result.
func convertWorkload(
	w workload,
	m *kube.Manifests,
	cfg *config.Config,
	declaredVolumes map[string]bool,
	overrideHits map[string]bool,
	envFileLines *[]string,
	envFileSeen map[string]bool,
	res *Result,
) error {
	name := serviceName(w, m)
	override := cfg.ServiceOverrideFor(name)
	if override.Skip || override.Image != "" || override.Build != nil {
		overrideHits[name] = true
	}
	if override.Skip {
		return nil
	}

	main, extras, warnings, err := convertPod(w, name, m, declaredVolumes, res.Compose, envFileLines, envFileSeen, res.ConfigFiles, res.EmptyDirs)
	if err != nil {
		return err
	}
	res.Warnings = append(res.Warnings, warnings...)

	// Auto-swap clustered chart images for vanilla dev equivalents
	// (Bitnami mongo replica-set → mongo:7, etc.). Runs before the
	// user's localk.yaml override so explicit `image:` always wins.
	// Passes envFileLines AND configFiles so the swap can resolve
	// auth values whether they came from a Secret (env_file) or
	// a *_FILE env pointing at a materialized secret on disk.
	if msg := applyDevSwap(name, &main, extras, override.PreserveImage, envFileLines, envFileSeen, res.ConfigFiles); msg != "" {
		res.Warnings = append(res.Warnings, msg)
		res.SwappedServices[name] = true
	}

	applyServiceOverride(&main, override)
	res.Compose.Services[name] = main
	for extraName, extra := range extras {
		res.Compose.Services[extraName] = extra
	}
	return nil
}

// serviceName decides what to call a workload in the compose file. We prefer
// the matched Service's name (which is what other services use as a hostname
// in production) over the workload's own name, so DNS continuity is
// preserved locally.
func serviceName(w workload, m *kube.Manifests) string {
	if svc := m.FindServiceForSelector(w.pod.Metadata.Labels); svc != nil {
		return svc.Metadata.Name
	}
	return w.name
}

// fqdnAliasesFor returns the set of compose network aliases that
// reproduce k8s in-cluster DNS for one workload.
//
// k8s services are reachable at any of:
//
//	<svc>
//	<svc>.<ns>
//	<svc>.<ns>.svc
//	<svc>.<ns>.svc.cluster.local
//
// Manifests routinely bake the longest form into ConfigMap/Secret
// env vars (Bitnami helm charts always do this), so the only safe
// approach is to alias every form to the compose service.
//
// For StatefulSets fronted by a headless Service, pods are also
// addressable as `<sts>-<i>.<headless>.<ns>.svc.cluster.local`. We
// generate aliases for ordinals 0..(replicas-1); compose still runs
// a single container, but at least the DNS resolves so apps that
// loop over `<sts>-0`, `<sts>-1`, `<sts>-2` connection strings hit
// the same backend instead of failing with ENOTFOUND.
//
// `mainName` is the compose service name we're attaching aliases to.
// It's deliberately omitted from the alias list (compose's embedded
// DNS already resolves it as the service name).
func fqdnAliasesFor(mainName string, w workload, services []*kube.Service) []string {
	if len(services) == 0 {
		return nil
	}
	replicas := w.replicas
	if replicas < 1 {
		replicas = 1
	}
	seen := map[string]bool{mainName: true}
	var out []string
	add := func(name string) {
		if name == "" || seen[name] {
			return
		}
		seen[name] = true
		out = append(out, name)
	}
	suffixes := func(name, ns string) {
		add(name)
		add(name + "." + ns)
		add(name + "." + ns + ".svc")
		add(name + "." + ns + ".svc.cluster.local")
	}
	for _, s := range services {
		ns := s.Metadata.Namespace
		if ns == "" {
			ns = "default"
		}
		suffixes(s.Metadata.Name, ns)

		// Headless services (clusterIP: None) front pod-level DNS.
		// In k8s the canonical pod FQDN is
		//   <pod-hostname>.<headless-svc>.<ns>.svc.cluster.local
		// Charts vary on what the pod hostname ends up being:
		//
		//   * StatefulSets default to "<sts>-<i>" so we emit those
		//     ordinal forms (mongodb-0, mongodb-1, ...).
		//   * Bitnami charts and many Deployments use the workload
		//     name directly (helm fullnameOverride, or `hostname:`
		//     on the pod template), giving "<workload>.<headless>...".
		//
		// We emit BOTH so we don't have to guess which form an env
		// var was baked with. Compose still runs one container per
		// workload; every alias resolves to the same backend.
		if s.Spec.ClusterIP == "None" {
			suffixes(w.name+"."+s.Metadata.Name, ns)
			if w.kindLabel == "statefulset" {
				for i := int32(0); i < replicas; i++ {
					pod := fmt.Sprintf("%s-%d", w.name, i)
					add(pod)
					suffixes(pod+"."+s.Metadata.Name, ns)
				}
			}
		}
	}
	sort.Strings(out)
	return out
}

// fqdnSelfHostnameFor picks a single FQDN to set as the compose
// service's `hostname:`. The reason this matters even when aliases
// already cover the FQDN: docker's embedded DNS resolver gives
// network aliases to *other* containers, but a container looking
// up its OWN FQDN goes through libc, which only sees what's in
// /etc/hosts. Without a matching hostname, apps that bind to their
// own FQDN (Erlang with USE_LONGNAME=true, Akka, etcd, Cassandra,
// rabbit's Erlang node) hang during startup.
//
// Returns "" when no headless service fronts the workload — short
// names work fine in that case and we don't want to surprise apps
// that look at gethostname() expecting an unqualified label.
func fqdnSelfHostnameFor(w workload, services []*kube.Service) string {
	for _, s := range services {
		if s.Spec.ClusterIP != "None" {
			continue
		}
		ns := s.Metadata.Namespace
		if ns == "" {
			ns = "default"
		}
		// Match the pod-hostname-equals-workload-name pattern that
		// Bitnami charts use; this is the single FQDN form most
		// likely to appear in baked-in env vars (RABBITMQ_NODE_NAME
		// etc.).
		return fmt.Sprintf("%s.%s.%s.svc.cluster.local", w.name, s.Metadata.Name, ns)
	}
	return ""
}

// convertPod walks every container in the pod and produces:
//   - main: the compose service for containers[0], named after the workload
//   - sidecars: a map of <main>-<container.Name> → compose.Service for any
//     additional containers, sharing main's network namespace via
//     network_mode: service:<main>. This mirrors the k8s pod model where
//     all containers share an IP and reach each other on localhost.
func convertPod(
	w workload,
	mainName string,
	m *kube.Manifests,
	declaredVolumes map[string]bool,
	out *compose.File,
	envFileLines *[]string,
	envFileSeen map[string]bool,
	configFiles map[string]string,
	emptyDirs map[string]bool,
) (compose.Service, map[string]compose.Service, []string, error) {
	var warnings []string

	containers := w.pod.Spec.Containers
	if len(containers) == 0 {
		return compose.Service{}, nil, nil, fmt.Errorf("%s %s has no containers", w.kindLabel, w.name)
	}

	// Pre-pass: identify volumes mounted by 2+ containers (main, sidecars,
	// or initContainers). These become shared scratch space — typical
	// patterns are "main writes logs, sidecar tails them" and "init
	// writes config, main reads it." Without promotion to a named volume,
	// each compose service gets its own anonymous mount and sharing
	// silently breaks.
	allContainers := append([]kube.Container{}, w.pod.Spec.InitContainers...)
	allContainers = append(allContainers, containers...)
	decision := shareDecisionFor(allContainers)

	extras := map[string]compose.Service{}

	// --- Init containers (run in declaration order, must complete before
	// main starts). Each init becomes a one-shot compose service with
	// restart: "no", and they form a depends_on chain so docker compose
	// runs them sequentially. The main service then depends_on the last
	// init with condition: service_completed_successfully.
	var initNames []string
	for i, c := range w.pod.Spec.InitContainers {
		s, w2 := buildContainerService(c, w, m, declaredVolumes, out, envFileLines, envFileSeen, decision, configFiles, emptyDirs)
		warnings = append(warnings, w2...)
		s.Restart = "no"
		name := mainName + "-" + c.Name
		if i > 0 {
			s.DependsOn = map[string]compose.DependsOnSpec{
				initNames[i-1]: {Condition: "service_completed_successfully"},
			}
		}
		extras[name] = s
		initNames = append(initNames, name)
	}

	// --- Main container.
	main, mainWarnings := buildContainerService(containers[0], w, m, declaredVolumes, out, envFileLines, envFileSeen, decision, configFiles, emptyDirs)
	warnings = append(warnings, mainWarnings...)

	// Service-derived ports are published only by the main's service.
	// Sidecars share that namespace, so a single host:port mapping covers
	// the whole pod.
	allMatched := m.FindAllServicesForSelector(w.pod.Metadata.Labels)
	if len(allMatched) > 0 {
		// Ports come from the first matched Service (typical pattern: a
		// regular ClusterIP fronts the workload, a headless sibling
		// exists alongside for StatefulSet pod DNS — the headless one
		// either has the same ports or none).
		for _, p := range allMatched[0].Spec.Ports {
			target := containerPortFromService(p, containers[0])
			main.Ports = append(main.Ports, fmt.Sprintf("%d:%d", p.Port, target))
		}
		// Network aliases let env vars baked with k8s cluster-DNS names
		// (e.g. `nats-0.nats-headless.default.svc.cluster.local`)
		// resolve to this compose service. Without them, apps that
		// pull connection strings from Secrets crash on DNS lookup.
		if aliases := fqdnAliasesFor(mainName, w, allMatched); len(aliases) > 0 {
			main.Networks = map[string]compose.ServiceNetwork{
				"default": {Aliases: aliases},
			}
		}
		// When a headless service fronts the workload, set the
		// container's hostname to the canonical FQDN so apps that
		// resolve their own FQDN at startup (Erlang, Akka, etcd)
		// can bind. Aliases alone don't cover self-resolution.
		if h := fqdnSelfHostnameFor(w, allMatched); h != "" {
			main.Hostname = h
		}
	}
	if len(initNames) > 0 {
		main.DependsOn = map[string]compose.DependsOnSpec{
			initNames[len(initNames)-1]: {Condition: "service_completed_successfully"},
		}
	}

	// --- Sidecars (run alongside main, sharing its network namespace).
	for _, c := range containers[1:] {
		sc, scWarnings := buildContainerService(c, w, m, declaredVolumes, out, envFileLines, envFileSeen, decision, configFiles, emptyDirs)
		warnings = append(warnings, scWarnings...)
		sc.NetworkMode = "service:" + mainName
		extras[mainName+"-"+c.Name] = sc
	}

	return main, extras, warnings, nil
}

// buildContainerService converts one k8s container into a generic compose
// Service — env, env_file, volumes, resource limits — with no role-specific
// tweaks. The caller decides what to do with the result based on whether
// the container is the main, a sidecar (set NetworkMode, drop Ports), or an
// init container (Restart="no", wire depends_on).
func buildContainerService(
	c kube.Container,
	w workload,
	m *kube.Manifests,
	declaredVolumes map[string]bool,
	out *compose.File,
	envFileLines *[]string,
	envFileSeen map[string]bool,
	decision shareDecision,
	configFiles map[string]string,
	emptyDirs map[string]bool,
) (compose.Service, []string) {
	multiMount := multiMountedNames(c)
	var warnings []string

	svc := compose.Service{
		Image:   c.Image,
		Restart: "unless-stopped",
	}
	// k8s command/args are shell strings meant for the container's
	// runtime to evaluate. Compose, however, runs an interpolation
	// pass over every string in the YAML at parse time and tries to
	// substitute `$VAR` / `${VAR}` / `$(cmd)` from its OWN env. To
	// keep the shell payload intact we escape every `$` to `$$`
	// (compose's documented escape) so it reaches the container
	// verbatim and the container's `sh` does the right thing at run
	// time. Same pattern applied to env values below.
	if len(c.Command) > 0 {
		svc.Entrypoint = escapeShellArgs(c.Command)
	}
	if len(c.Args) > 0 {
		svc.Command = escapeShellArgs(c.Args)
	}

	// --- Environment ---
	env := map[string]string{}

	// envFrom comes first so explicit env entries can override.
	for _, ef := range c.EnvFrom {
		switch {
		case ef.ConfigMapRef != nil:
			cm := m.FindConfigMap(ef.ConfigMapRef.Name)
			if cm == nil {
				warnings = append(warnings, fmt.Sprintf(
					"%s %q references ConfigMap %q via envFrom but it is not defined in the input",
					w.kindLabel, w.name, ef.ConfigMapRef.Name,
				))
				continue
			}
			for k, v := range cm.Data {
				env[ef.Prefix+k] = v
			}
		case ef.SecretRef != nil:
			sec := m.FindSecret(ef.SecretRef.Name)
			if sec == nil {
				warnings = append(warnings, fmt.Sprintf(
					"%s %q references Secret %q via envFrom but it is not defined in the input",
					w.kindLabel, w.name, ef.SecretRef.Name,
				))
				continue
			}
			for k, v := range secretValues(sec) {
				key := ef.Prefix + k
				addEnvFileLine(envFileLines, envFileSeen, key, v)
			}
			svc.EnvFile = appendUnique(svc.EnvFile, ".env")
		}
	}

	// Walk env entries in declaration order so $(VAR) references inside a
	// later value can resolve against earlier env vars (the same semantics
	// k8s applies at pod startup).
	for _, e := range c.Env {
		switch {
		case e.ValueFrom == nil:
			env[e.Name] = expandRefs(e.Value, env)
		case e.ValueFrom.FieldRef != nil:
			v, ok := resolveFieldRef(e.ValueFrom.FieldRef.FieldPath, w)
			if !ok {
				warnings = append(warnings, fmt.Sprintf(
					"env %q in %s %q uses fieldPath %q which has no local equivalent; leaving unset",
					e.Name, w.kindLabel, w.name, e.ValueFrom.FieldRef.FieldPath,
				))
				continue
			}
			env[e.Name] = v
		case e.ValueFrom.ConfigMapKeyRef != nil:
			ref := e.ValueFrom.ConfigMapKeyRef
			cm := m.FindConfigMap(ref.Name)
			if cm == nil {
				warnings = append(warnings, fmt.Sprintf(
					"env %q in %s %q references ConfigMap %q which is not defined",
					e.Name, w.kindLabel, w.name, ref.Name,
				))
				continue
			}
			env[e.Name] = cm.Data[ref.Key]
		case e.ValueFrom.SecretKeyRef != nil:
			ref := e.ValueFrom.SecretKeyRef
			sec := m.FindSecret(ref.Name)
			if sec == nil {
				warnings = append(warnings, fmt.Sprintf(
					"env %q in %s %q references Secret %q which is not defined",
					e.Name, w.kindLabel, w.name, ref.Name,
				))
				continue
			}
			vals := secretValues(sec)
			addEnvFileLine(envFileLines, envFileSeen, e.Name, vals[ref.Key])
			svc.EnvFile = appendUnique(svc.EnvFile, ".env")
		}
	}
	if len(env) > 0 {
		// Compose interpolates `$VAR` / `${VAR}` patterns in env
		// values at parse time. After expandRefs has resolved any
		// k8s `$(VAR)` downward-API references, the only `$` left
		// in a value is meant to reach the container literally —
		// either it's a shell variable for the container to expand
		// at runtime (`$XDG_CONFIG_HOME` in nats-box bootstrap), or
		// it's part of a value (`pass$word`). Both want to survive
		// compose's interpolation pass, so we double the dollars.
		svc.Environment = escapeEnvValues(env)
	}

	// --- Volumes ---
	for _, vm := range c.VolumeMounts {
		volSrc := findVolume(w.allVolumes(), vm.Name)
		if volSrc == nil {
			warnings = append(warnings, fmt.Sprintf(
				"%s %q has volumeMount %q with no matching volume in the pod spec",
				w.kindLabel, w.name, vm.Name,
			))
			continue
		}
		entry, declareName, declared, files, perEntryWarnings := volumeEntryFor(volSrc, vm, decision, multiMount[vm.Name], w.name, m)
		if entry != nil {
			svc.Volumes = append(svc.Volumes, entry)
		}
		// Bind-mounted emptyDir paths need to exist on the host
		// before compose up — record relative to out-dir so the
		// CLI can `mkdir -p` + chmod 0777 each one.
		if dir := emptyDirHostPath(entry); dir != "" {
			emptyDirs[dir] = true
		}
		if declared && !declaredVolumes[declareName] {
			out.Volumes[declareName] = compose.Volume{}
			declaredVolumes[declareName] = true
		}
		// Merge any materialized ConfigMap/Secret files into the
		// shared map. Same CM mounted in multiple containers is a
		// no-op write; each key produces the same content.
		for path, content := range files {
			configFiles[path] = content
		}
		warnings = append(warnings, perEntryWarnings...)
	}

	// --- Resource limits ---
	if c.Resources.Limits.Memory != "" || c.Resources.Limits.CPU != "" {
		svc.Deploy = &compose.Deploy{
			Resources: compose.DeployResources{
				Limits: &compose.ResourceSpec{
					CPUs:   normalizeCPU(c.Resources.Limits.CPU),
					Memory: normalizeMemory(c.Resources.Limits.Memory),
				},
			},
		}
	}

	sort.Strings(svc.EnvFile)
	return svc, warnings
}

// shareDecision is the pod-level verdict the volume code uses to
// decide whether each mount becomes a named-volume mount or an
// anonymous scratch mount.
type shareDecision struct {
	// pairShared lists (name|mountPath) keys that appear in 2+
	// containers — the explicit "this exact path is shared" case
	// (init→main plugin dir, main+sidecar log dir).
	pairShared map[string]bool
	// nameInContainers counts how many distinct containers reference
	// each volume name. ≥2 means there's potential cross-container
	// sharing even if mount paths differ — the simple init+main case
	// where init has /out and main has /etc/app, both meaning to
	// share the underlying volume.
	nameInContainers map[string]int
}

// shareDecisionFor analyzes the pod's containers and returns the
// promotion-vs-anonymous information needed for volumeEntryFor.
// The richer return shape (vs a flat shared-name set) lets
// volumeEntryFor handle all three real-world patterns:
//
//  1. Simple init+main with different paths (config at /out and /etc/app)
//     — by-name shared, each container mounts once → promote.
//  2. Bitnami main with one volume at many paths
//     — by-name shared but multi-mounted in this container → only
//     paths that are ALSO in another container promote; the rest
//     stay anonymous so each path is independent scratch.
//  3. Single-container scratch — neither shared → anonymous.
func shareDecisionFor(containers []kube.Container) shareDecision {
	d := shareDecision{
		pairShared:       map[string]bool{},
		nameInContainers: map[string]int{},
	}
	pairCount := map[string]int{}
	for _, c := range containers {
		seenPair := map[string]bool{}
		seenName := map[string]bool{}
		for _, vm := range c.VolumeMounts {
			pkey := vm.Name + "|" + vm.MountPath
			if !seenPair[pkey] {
				seenPair[pkey] = true
				pairCount[pkey]++
			}
			seenName[vm.Name] = true
		}
		for name := range seenName {
			d.nameInContainers[name]++
		}
	}
	for k, n := range pairCount {
		if n > 1 {
			d.pairShared[k] = true
		}
	}
	return d
}

// shouldPromote is the rule for a specific mount in a specific
// container. inMultiMountContainer is per-container — a volume might
// be multi-mounted in main but single-mounted in init, and the rule
// applies independently to each.
func (d shareDecision) shouldPromote(volumeName, mountPath string, inMultiMountContainer bool) bool {
	if d.pairShared[volumeName+"|"+mountPath] {
		return true
	}
	if d.nameInContainers[volumeName] >= 2 && !inMultiMountContainer {
		return true
	}
	return false
}

// multiMountedNames returns the set of volume names this specific
// container mounts at more than one path WITHOUT subPath — the
// Bitnami per-path scratch pattern that broke when promoted (all
// six paths ended up showing the same data). Mounts that DO use
// subPath are excluded from this count: subPath partitions the
// volume into per-path subdirectories, so promoting is safe and
// in fact required (init+main share via subpath).
func multiMountedNames(c kube.Container) map[string]bool {
	count := map[string]int{}
	for _, vm := range c.VolumeMounts {
		if vm.SubPath != "" {
			continue
		}
		count[vm.Name]++
	}
	out := map[string]bool{}
	for name, n := range count {
		if n > 1 {
			out[name] = true
		}
	}
	return out
}

func findVolume(vols []kube.Volume, name string) *kube.Volume {
	for i := range vols {
		if vols[i].Name == name {
			return &vols[i]
		}
	}
	return nil
}

// volumeEntryFor returns the compose-side volume mount info for a
// given k8s volume reference, plus any files that need to be
// materialized on disk (for ConfigMap/Secret-backed volumes which
// have no native compose equivalent — we write the data to files
// under the out-dir and bind-mount the directory).
//
// Returns:
//   - mount: the entry to append to the service's `volumes:` list
//     (empty string = no mount, e.g. for unsupported types)
//   - declareName: name of a top-level volume to declare (PVCs and
//     promoted shared emptyDirs); empty when no top-level decl
//   - declared: whether the caller should add declareName to volumes
//   - files: relative-path → content to write before `up` (under the
//     out-dir's `configs/` or `secrets/` tree)
//   - warnings: things the user should know (missing CM/Secret refs,
//     mostly)
//
// decision carries the pod-level share analysis; inMultiMount says
// whether THIS specific container mounts this volume name at >1 path
// without distinguishing subPaths (the Bitnami per-path scratch
// pattern). Together they decide whether an emptyDir gets promoted
// to a named compose volume (so multiple containers see the same
// data) or stays anonymous (so each path is independent scratch).
//
// Returns `any` so the entry can be either compose's short string
// form ("name:/path") or a long-form *compose.MountLong struct;
// the latter is currently used for PVC + subPath only. emptyDir
// subPath emits a host bind mount instead — see below.
func volumeEntryFor(v *kube.Volume, vm kube.VolumeMount, decision shareDecision, inMultiMount bool, workloadName string, m *kube.Manifests) (any, string, bool, map[string]string, []string) {
	switch {
	case v.PVC != nil:
		if vm.SubPath != "" {
			return &compose.MountLong{
				Type:   "volume",
				Source: v.PVC.ClaimName,
				Target: vm.MountPath,
				Volume: &compose.MountVolumeOpts{Subpath: vm.SubPath},
			}, v.PVC.ClaimName, true, nil, nil
		}
		return fmt.Sprintf("%s:%s", v.PVC.ClaimName, vm.MountPath), v.PVC.ClaimName, true, nil, nil
	case v.EmptyDir != nil:
		// emptyDir with subPath is the Bitnami chart pattern: one
		// volume sliced into many per-path subdirectories that init
		// containers populate and main containers read. Compose's
		// volume.subpath looks like the right tool but breaks in
		// practice — it requires the subdir to already exist in the
		// volume on first attach, which it doesn't (compose has no
		// `pre-create` step). Named volumes also start root-owned,
		// blocking non-root container writes (Bitnami's UID 1001).
		//
		// Bind-mount to a host dir under out-dir/volumes/ instead.
		// We mkdir it at generate time with mode 0777 so any
		// container UID can read/write, and init+main share via
		// the host filesystem the same way k8s shares via the
		// kubelet's emptyDir backing.
		if vm.SubPath != "" {
			host := fmt.Sprintf("./volumes/%s/%s/%s", workloadName, v.Name, vm.SubPath)
			return fmt.Sprintf("%s:%s", host, vm.MountPath), "", false, nil, nil
		}
		if decision.shouldPromote(v.Name, vm.MountPath, inMultiMount) {
			// Cross-container shared emptyDir without subPath: bind
			// to a single host dir for the same auto-create + UID
			// reasons. (Init+main test case still works — both bind
			// the same host path, see the same data.)
			host := fmt.Sprintf("./volumes/%s/%s", workloadName, v.Name)
			return fmt.Sprintf("%s:%s", host, vm.MountPath), "", false, nil, nil
		}
		return vm.MountPath, "", false, nil, nil
	case v.HostPath != nil:
		src := v.HostPath.Path
		if vm.SubPath != "" {
			src = path.Join(src, vm.SubPath)
		}
		return fmt.Sprintf("%s:%s", src, vm.MountPath), "", false, nil, nil
	case v.ConfigMap != nil:
		entry, decl, declared, files, warns := materializeConfigMap(v.ConfigMap.Name, vm, m)
		return mountStringOrNil(entry), decl, declared, files, warns
	case v.Secret != nil:
		entry, decl, declared, files, warns := materializeSecret(v.Secret.SecretName, vm, m)
		return mountStringOrNil(entry), decl, declared, files, warns
	case v.Projected != nil:
		entry, decl, declared, files, warns := materializeProjected(v, vm, m)
		return mountStringOrNil(entry), decl, declared, files, warns
	}
	return nil, "", false, nil, []string{fmt.Sprintf(
		"volumeMount %q on %s has an unsupported volume type (only emptyDir, hostPath, configMap, secret, projected, and PVCs are handled); skipping",
		vm.Name, vm.MountPath,
	)}
}

// mountStringOrNil returns nil for empty mount strings (skip) and
// the string itself otherwise. Lets the materialize* helpers stay
// string-typed while the public entry point hands back any.
func mountStringOrNil(s string) any {
	if s == "" {
		return nil
	}
	return s
}

// emptyDirHostPath extracts the host-side directory we should pre-create
// for an emptyDir bind-mount entry. We only pre-create the VOLUME ROOT,
// not per-subpath leaf dirs:
//
//   - Init containers commonly do `cp -r src/ /emptydir/<subpath>` and
//     rely on the destination NOT existing so cp creates it as a copy
//     (otherwise cp puts the source as a nested subdir, breaking the
//     expected layout — Bitnami rabbit's plugins dir hits this exact
//     case).
//   - Docker auto-creates a missing bind-mount source as a 0755
//     root-owned dir, which IS a problem for non-root containers, but
//     init containers in Bitnami charts always run early enough to
//     populate the subpath before main mounts it.
//
// The volume root we pre-create with mode 0777 so the init can write
// into it as any UID. Sub-path leaves are left to the init or docker.
func emptyDirHostPath(entry any) string {
	s, ok := entry.(string)
	if !ok {
		return ""
	}
	const prefix = "./volumes/"
	if !strings.HasPrefix(s, prefix) {
		return ""
	}
	colon := strings.IndexByte(s, ':')
	if colon < 0 {
		return ""
	}
	full := strings.TrimPrefix(s[:colon], "./")
	// Trim back to the "<workload>/<volume>" volume root.
	parts := strings.Split(full, "/")
	if len(parts) < 3 {
		return ""
	}
	return strings.Join(parts[:3], "/")
}

// materializeConfigMap turns a `volumes: { configMap: { name: X } }`
// reference into:
//   - a bind-mount entry pointing at out-dir/configs/X
//   - one file per key in the ConfigMap's data
//
// The mount is read-only because k8s defaults configMap volumes to
// read-only — apps that try to write back would silently succeed
// locally and fail in prod, which is a worse failure mode than just
// rejecting writes everywhere.
func materializeConfigMap(name string, vm kube.VolumeMount, m *kube.Manifests) (string, string, bool, map[string]string, []string) {
	cm := m.FindConfigMap(name)
	if cm == nil {
		return "", "", false, nil, []string{fmt.Sprintf(
			"volumeMount %q references ConfigMap %q which is not defined; skipping the mount (the container will see an empty directory at %s)",
			vm.Name, name, vm.MountPath,
		)}
	}
	files := map[string]string{}
	for key, val := range cm.Data {
		files[fmt.Sprintf("configs/%s/%s", name, key)] = val
	}
	// k8s subPath mounts a single key from the ConfigMap as a file at
	// the mount path (e.g. /scripts/setup.sh) instead of the whole CM
	// directory. Without this, Docker bind-mounts the entire dir and
	// the container sees a directory where it expects a file —
	// "exec: /scripts/setup.sh: is a directory" or similar.
	if vm.SubPath != "" {
		if _, ok := cm.Data[vm.SubPath]; !ok {
			return "", "", false, files, []string{fmt.Sprintf(
				"volumeMount %q on ConfigMap %q has subPath %q but that key is not in the ConfigMap data",
				vm.Name, name, vm.SubPath,
			)}
		}
		mount := fmt.Sprintf("./configs/%s/%s:%s:ro", name, vm.SubPath, vm.MountPath)
		return mount, "", false, files, nil
	}
	mount := fmt.Sprintf("./configs/%s:%s:ro", name, vm.MountPath)
	return mount, "", false, files, nil
}

// materializeSecret is the Secret-volume sibling of materializeConfigMap.
// Decodes base64 data + merges stringData (matching k8s semantics)
// before writing files. A warning surfaces because the resulting
// files contain real secret values — same hazard the .env file
// already has, restated for the volume case so users don't miss it.
func materializeSecret(name string, vm kube.VolumeMount, m *kube.Manifests) (string, string, bool, map[string]string, []string) {
	sec := m.FindSecret(name)
	if sec == nil {
		return "", "", false, nil, []string{fmt.Sprintf(
			"volumeMount %q references Secret %q which is not defined; skipping the mount",
			vm.Name, name,
		)}
	}
	values := secretValues(sec) // existing helper: merges Data (b64) and StringData
	files := map[string]string{}
	for key, val := range values {
		files[fmt.Sprintf("secrets/%s/%s", name, key)] = val
	}
	warning := fmt.Sprintf(
		"Secret %q materialized as files under secrets/%s/. These are real cluster secret values — add `secrets/` to .gitignore and never commit them.",
		name, name,
	)
	// subPath mounts a single secret key as a file (e.g. an RSA
	// private key at /etc/keys/private.pem) instead of the whole
	// Secret directory.
	if vm.SubPath != "" {
		if _, ok := values[vm.SubPath]; !ok {
			return "", "", false, files, []string{fmt.Sprintf(
				"volumeMount %q on Secret %q has subPath %q but that key is not in the Secret data",
				vm.Name, name, vm.SubPath,
			)}
		}
		mount := fmt.Sprintf("./secrets/%s/%s:%s:ro", name, vm.SubPath, vm.MountPath)
		return mount, "", false, files, []string{warning}
	}
	mount := fmt.Sprintf("./secrets/%s:%s:ro", name, vm.MountPath)
	return mount, "", false, files, []string{warning}
}

// materializeProjected turns a `volumes: { projected: { sources: [...] } }`
// reference into a single bind-mount entry plus a flat set of
// materialized files combining every source into one directory.
//
// k8s projected volumes are how Bitnami helm charts (and many
// others) deliver multi-file secrets — rabbitmq's chart projects
// rabbitmq-password and rabbitmq-erlang-cookie into the same
// /opt/bitnami/rabbitmq/secrets directory, then the entrypoint
// reads each file by name. Without projected support, localk
// would silently drop the mount, the container would find no
// secrets, and rabbit would hang forever before opening AMQP.
//
// The output dir lands under `secrets/<vol>/` if any source is a
// Secret (so the file mode logic in cmd/localk picks 0644 — needed
// for non-root containers to read), or `configs/<vol>/` otherwise.
// Keys are flattened across all sources; on conflict, later sources
// win, matching k8s behavior.
func materializeProjected(v *kube.Volume, vm kube.VolumeMount, m *kube.Manifests) (string, string, bool, map[string]string, []string) {
	var warnings []string
	files := map[string]string{}
	hasSecret := false
	allKeys := map[string]string{}

	for _, src := range v.Projected.Sources {
		switch {
		case src.Secret != nil:
			hasSecret = true
			sec := m.FindSecret(src.Secret.Name)
			if sec == nil {
				warnings = append(warnings, fmt.Sprintf(
					"projected volume %q references Secret %q which is not defined; skipping that source",
					v.Name, src.Secret.Name,
				))
				continue
			}
			values := secretValues(sec)
			collect(allKeys, values, src.Secret.Items)
		case src.ConfigMap != nil:
			cm := m.FindConfigMap(src.ConfigMap.Name)
			if cm == nil {
				warnings = append(warnings, fmt.Sprintf(
					"projected volume %q references ConfigMap %q which is not defined; skipping that source",
					v.Name, src.ConfigMap.Name,
				))
				continue
			}
			collect(allKeys, cm.Data, src.ConfigMap.Items)
		}
	}

	prefix := "configs"
	if hasSecret {
		prefix = "secrets"
		warnings = append(warnings, fmt.Sprintf(
			"projected volume %q materialized as files under %s/%s/. These include real cluster secret values — add `secrets/` to .gitignore.",
			v.Name, prefix, v.Name,
		))
	}
	for key, val := range allKeys {
		files[fmt.Sprintf("%s/%s/%s", prefix, v.Name, key)] = val
	}

	// subPath on a projected volume mounts a single key as a file
	// (just like ConfigMap/Secret subPath). Match that behavior.
	if vm.SubPath != "" {
		if _, ok := allKeys[vm.SubPath]; !ok {
			return "", "", false, files, append(warnings, fmt.Sprintf(
				"volumeMount %q on projected volume %q has subPath %q but that key is not present in any source",
				vm.Name, v.Name, vm.SubPath,
			))
		}
		mount := fmt.Sprintf("./%s/%s/%s:%s:ro", prefix, v.Name, vm.SubPath, vm.MountPath)
		return mount, "", false, files, warnings
	}
	mount := fmt.Sprintf("./%s/%s:%s:ro", prefix, v.Name, vm.MountPath)
	return mount, "", false, files, warnings
}

// collect flattens a source's data into the accumulated key map,
// applying items remapping when present (k8s lets a projected
// source select specific keys and rename their on-disk path). With
// no items, every key is projected under its own name.
func collect(dst, src map[string]string, items []kube.KeyToPath) {
	if len(items) == 0 {
		for k, v := range src {
			dst[k] = v
		}
		return
	}
	for _, it := range items {
		if v, ok := src[it.Key]; ok {
			dst[it.Path] = v
		}
	}
}

// containerPortFromService picks the right container-side port for a Service
// port mapping. If targetPort is set and numeric, use it. If it's a string,
// look up the named port in the container. Otherwise default to the service
// port itself.
func containerPortFromService(p kube.ServicePort, c kube.Container) int32 {
	if p.TargetPort == nil {
		return p.Port
	}
	switch v := p.TargetPort.(type) {
	case int:
		return int32(v)
	case int32:
		return v
	case int64:
		return int32(v)
	case string:
		// numeric string?
		if n, err := strconv.Atoi(v); err == nil {
			return int32(n)
		}
		// named port — look it up in the container's port list
		for _, cp := range c.Ports {
			if cp.Name == v {
				return cp.ContainerPort
			}
		}
	}
	return p.Port
}

// secretValues returns the decoded key/value pairs from a Secret, merging
// stringData (plain) and data (base64-encoded). stringData wins on conflict,
// matching Kubernetes' own semantics.
func secretValues(s *kube.Secret) map[string]string {
	out := map[string]string{}
	for k, v := range s.Data {
		dec, err := base64.StdEncoding.DecodeString(v)
		if err == nil {
			out[k] = string(dec)
		} else {
			// Not base64 — pass through as-is. Some manifests do this.
			out[k] = v
		}
	}
	for k, v := range s.StringData {
		out[k] = v
	}
	return out
}

func addEnvFileLine(lines *[]string, seen map[string]bool, key, value string) {
	if seen[key] {
		return
	}
	seen[key] = true
	// Quote the value to be safe; we escape any embedded double quotes.
	escaped := strings.ReplaceAll(value, `"`, `\"`)
	*lines = append(*lines, fmt.Sprintf(`%s="%s"`, key, escaped))
}

func appendUnique(slice []string, item string) []string {
	for _, s := range slice {
		if s == item {
			return slice
		}
	}
	return append(slice, item)
}

// normalizeCPU converts a k8s CPU quantity ("500m", "1") into a compose-style
// fractional CPU string ("0.5", "1.0"). Compose accepts fractional cpus.
func normalizeCPU(s string) string {
	if s == "" {
		return ""
	}
	if strings.HasSuffix(s, "m") {
		num := strings.TrimSuffix(s, "m")
		if n, err := strconv.Atoi(num); err == nil {
			return fmt.Sprintf("%.3f", float64(n)/1000.0)
		}
	}
	return s
}

// escapeShellArgs doubles every `$` in each element so compose's
// parse-time variable interpolation leaves the args alone. The
// escape is compose's own (`$$` → literal `$`); the container's
// shell never sees the doubled form because compose un-escapes
// before passing the args to the container.
func escapeShellArgs(args []string) []string {
	if len(args) == 0 {
		return args
	}
	out := make([]string, len(args))
	for i, a := range args {
		out[i] = escapeDollars(a)
	}
	return out
}

// escapeEnvValues runs the same escape over the values of an env
// map. Keys are left untouched (env-var names can't contain `$` in
// any sane setup).
func escapeEnvValues(env map[string]string) map[string]string {
	out := make(map[string]string, len(env))
	for k, v := range env {
		out[k] = escapeDollars(v)
	}
	return out
}

// escapeDollars replaces every `$` with `$$`. We don't try to be
// clever about which dollars are "real" shell variables vs. literal
// — compose treats every `$` as an interpolation trigger, so every
// `$` we want to pass through needs the escape.
func escapeDollars(s string) string {
	if !strings.Contains(s, "$") {
		return s
	}
	return strings.ReplaceAll(s, "$", "$$")
}

// normalizeMemory converts a k8s memory quantity to a compose-compatible
// integer-bytes string.
//
// k8s and compose use different memory unit grammars:
//   - k8s accepts both binary (Ki, Mi, Gi, Ti — powers of 1024) and decimal
//     (K, M, G, T — powers of 1000) suffixes.
//   - compose accepts only decimal suffixes (b, k/kb, m/mb, g/gb) plus plain
//     bytes as a number. Binary suffixes (Mi/Gi) are rejected with
//     "invalid suffix" — that's the bug this fixes.
//
// We normalize to plain bytes, which compose accepts losslessly. The
// generated YAML reads "536870912" instead of "512Mi" — less friendly to
// eyeball but unambiguous and correct on every compose version. Comments
// in the generated file already point users at `localk generate` rather
// than hand-editing, so readability of the byte count isn't a real
// regression.
//
// Unknown / unparseable inputs pass through unchanged so a future k8s
// suffix or a malformed value surfaces as a compose error rather than
// silently dropping the limit.
func normalizeMemory(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	i := 0
	for i < len(s) && (s[i] == '.' || (s[i] >= '0' && s[i] <= '9')) {
		i++
	}
	if i == 0 || i == len(s) {
		// No leading digits, or no suffix to convert — pass through.
		return s
	}
	valStr, suffix := s[:i], s[i:]

	var multiplier int64
	switch strings.ToLower(suffix) {
	case "ki":
		multiplier = 1 << 10
	case "mi":
		multiplier = 1 << 20
	case "gi":
		multiplier = 1 << 30
	case "ti":
		multiplier = 1 << 40
	case "k":
		multiplier = 1000
	case "m":
		multiplier = 1000 * 1000
	case "g":
		multiplier = 1000 * 1000 * 1000
	case "t":
		multiplier = 1000 * 1000 * 1000 * 1000
	default:
		return s
	}

	val, err := strconv.ParseFloat(valStr, 64)
	if err != nil {
		return s
	}
	return strconv.FormatInt(int64(val*float64(multiplier)), 10)
}
